# Generated by Django 3.2.dev20201112141917 on 2020-11-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_joined',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
