# Generated by Django 3.2.dev20201112141917 on 2020-11-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20201123_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
