# Generated by Django 3.2.dev20201112141917 on 2020-11-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armazon', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IzquierdaDerecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izquierda_derecha', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LejosCerca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lejos_cerca', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('especialidad', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medico_asignado', to='clinica.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('asistio', models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='asistencia_turno', to='clinica.asistenciaturno')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medico_turno', to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paciente_turno', to='clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=64)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('armazon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incluye_armazon', to='clinica.armazon')),
                ('izquierda_derecha', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='izquierda_o_derecha', to='clinica.izquierdaderecha')),
                ('lejos_cerca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lejos_o_cerca', to='clinica.lejoscerca')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='estado_de_pedido', to='clinica.estadopedido')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paciente_producto', to='clinica.paciente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='producto_pedido', to='clinica.producto')),
                ('tipo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='forma_de_pago', to='clinica.formadepago')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medico_historial', to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paciente_historial', to='clinica.paciente')),
            ],
        ),
    ]
