# Generated by Django 3.2.dev20201112141917 on 2020-11-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_pedido_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vendedor_pedido', to='clinica.vendedor'),
        ),
    ]
