# Generated by Django 3.2.dev20201112141917 on 2020-11-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20201115_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_de_pago',
        ),
        migrations.DeleteModel(
            name='FormaDePago',
        ),
    ]
