# Generated by Django 3.2.dev20201112141917 on 2020-11-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_auto_20201115_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_de_pago',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='forma_de_pago', to='clinica.formadepago'),
        ),
    ]
