# Generated by Django 3.2.dev20201112141917 on 2020-11-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20201115_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formadepago',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
