# Generated by Django 3.2.dev20201112141917 on 2020-11-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_auto_20201116_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armazon', models.CharField(default='No aplica', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IzquierdaDerecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izquierda_derecha', models.CharField(default='No aplica', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LejosCerca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lejos_cerca', models.CharField(default='No aplica', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='armazon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incluye_armazon', to='clinica.armazon'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='izquierda_derecha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='izquierda_o_derecha', to='clinica.izquierdaderecha'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lejos_cerca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lejos_o_cerca', to='clinica.lejoscerca'),
        ),
    ]
