# Generated by Django 3.2.dev20201112141917 on 2020-11-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_auto_20201116_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='username',
            field=models.CharField(default='medico', max_length=64),
        ),
    ]
