# Generated by Django 3.2.dev20201112141917 on 2020-11-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_medico_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.RESTRICT, related_name='medico_asignado', to='clinica.medico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
