# Generated by Django 3.2.dev20201112141917 on 2020-11-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_auto_20201117_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='medico_asignado', to='clinica.medico'),
        ),
    ]
