# Generated by Django 3.2.dev20201112141917 on 2020-11-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0012_alter_paciente_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='armazon',
            name='armazon',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='izquierdaderecha',
            name='izquierda_derecha',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='lejoscerca',
            name='lejos_cerca',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='forma_de_pago', to='clinica.formadepago'),
        ),
    ]
