# Generated by Django 3.2.dev20201112141917 on 2020-11-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_auto_20201118_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='estado_de_pedido', to='clinica.estadopedido'),
        ),
    ]
