# Generated by Django 3.2.dev20201112141917 on 2020-11-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
    ]
