# Generated by Django 3.2.dev20201112141917 on 2020-11-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0015_asistenciaturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='asistio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='asistencia_turno', to='clinica.asistenciaturno'),
        ),
    ]
